services:
  # this downloads the models once on to host machine and exits
  model-downloader:
    build: 
      context: ./model-downloader
    image: rmrhub/model-downloader:v0.1.1
    volumes:
      - ./${DATA_DIR}:/app/${DATA_DIR}  
    env_file:
      - .env
  
  # this is the embeddings server that creates and retrieves embeddings that are stored in the doc-store server 
  embeddings-server:
    build: 
      context: ./embeddings-server
      dockerfile: Dockerfile
    hostname: embeddings-server
    image: rmrhub/sia-embeddings-server:v0.1.1
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # Use environment variables from .env file
    volumes:
      - ./${DATA_DIR}:/app/${DATA_DIR}  # Mount shared data directory
    depends_on:
      - model-downloader
    ports:
      - "8002:8002"  # Expose port for the embeddings server API    
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # this is the api server for admin and chat purposes
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    hostname: api-server # required for web-server to proxy_pass
    image: rmrhub/sia-api-server:v0.1.1
    environment:
      - PYTHONUNBUFFERED=1 # can be removed in production
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./${DATA_DIR}:/app/${DATA_DIR}:rw  # Shared data directory
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    #depends_on:
    #  - embeddings-server
    command: >
      sh -c "chmod -R 777 /app/${DATA_DIR} && uvicorn main:app --host 0.0.0.0 --port 8080 --workers ${API_NO_WORKERS:-1}"

  # this is the proxy cum web-server for chat
  web-server:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    image: rmrhub/sia-web-server:v0.1.1
    ports:
      - "3000:3000"
      # Uncomment the following line to expose HTTPS port
      # - "443:443"
    depends_on:
      - api-server
    volumes:
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf:ro
